### ISSUE TITLE
Merge PhysBone with rotation mode fix is incompatbile with Merge Bone

### ISSUE THREAD

**Issue by nil-vr** [anatawa12/AvatarOptimizer#1339]
このスカートはPhysBone ComponentsとPhysBone Transformsが多いすぎています。
![image](https://github.com/user-attachments/assets/2dc7ffa8-d816-47d6-9a15-97833adb181f)

Merge PhysBoneを使ってPhysBone Componentsを下がれます。

![image](https://github.com/user-attachments/assets/e48b4d55-4471-470a-a1b5-897b428690ef)

Merge Boneを使ってPhysBone Transformsを下がれます。

![image](https://github.com/user-attachments/assets/62894a11-a4d8-4c1f-b630-7347c0af757e)

でも同じ時間でMerge BoneとMerge PhysBoneを使うとMerge Boneはboneの数が下がりません。

![image](https://github.com/user-attachments/assets/6b6d7eca-8458-4203-8cca-93b2cc6a0fcd)

1.8.0-rc.6

**Comment by anatawa12** [comment]
It looks you're using machine translation. Please do not use them or please put both original and translated text on issues.

Basically, MergeBone on the moving bones including PhysBone may work but is unsupported. (But I’ll work to not break previously working configration)

you're using MergePhysBone with rotation mode fix, it's expected to not work since rotation mode fix would rearrange hierarchy. I think it would be better to note this with warning/error, but I don't want to fix for now.
